### ISSUE TITLE
Reserve `Point` for a `Domain`?

### ISSUE THREAD

**Issue by dlfivefifty** [daanhb/Domains.jl#6]
Defining `const Point{N,T} = SVector{N,T}` prevents the useful definition
```julia
struct Point{N,T} <: Domain{T}
  x::T
end
```

**Comment by daanhb** [comment]
Makes sense for `Point` to be a domain, yes. The only goal of `Point` before was to abstract away the choice between `SVector` and other implementations of fixed size vectors. But we settle on `SVector` right now.
